main: me.confuser.offlineplayer.OfflinePlayerPlugin
name: OfflinePlayer
version: ${project.version}
website: http://www.frostcast.net
authors: [confuserr]
depend: [PlayerIdAPI]
softdepend: [Essentials]
commands:
  offline:
    description: "OfflinePlayer base command"
    usage: "/offline <subCommand> <args>"